[package]
name = "RustySNES"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.14.5"
bitflags = "2.5.0"
spin = "0.9.8"
